steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/mizincew/gcp-cd-tutorial"]
    env: ["PROJECT_ROOT=github.com/mizincew/gcp-cd-tutorial"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/tutorial-230820/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/tutorial-230820/gcp-cd-codelab:$REVISION_ID"
